name: Tests

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2.3.1
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install package
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip    
        bash build_proxnest.sh
    
    - name: Run tests
      run: |
        pytest --cov-report term --cov=ProxNest --cov-config=.coveragerc 
        codecov --token eb6c2b0b-4ad0-4c7d-9d8a-1d22cdf79673

